---
# QBITEL ArgoCD AppProject
# Defines boundaries for QBITEL applications
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: qbitel
  namespace: argocd
  labels:
    app.kubernetes.io/name: qbitel-project
    app.kubernetes.io/part-of: qbitel-gitops
  # Finalizer to prevent accidental deletion
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: QBITEL Enterprise Security Platform

  # Source repositories
  sourceRepos:
    - https://github.com/yazhsab/qbitel.git
    - https://github.com/yazhsab/qbitel-config.git
    - https://charts.bitnami.com/bitnami
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://helm.elastic.co
    - https://charts.jetstack.io
    - https://argoproj.github.io/argo-helm

  # Destination clusters and namespaces
  destinations:
    # Development
    - namespace: qbitel-dev
      server: https://kubernetes.default.svc
    - namespace: qbitel-dev-*
      server: https://kubernetes.default.svc

    # Staging
    - namespace: qbitel-staging
      server: https://kubernetes.default.svc
    - namespace: qbitel-staging-*
      server: https://kubernetes.default.svc

    # Production
    - namespace: qbitel-prod
      server: https://kubernetes.default.svc
    - namespace: qbitel-prod-*
      server: https://kubernetes.default.svc

    # Infrastructure namespaces
    - namespace: qbitel-vllm
      server: https://kubernetes.default.svc
    - namespace: qbitel-observability
      server: https://kubernetes.default.svc
    - namespace: qbitel-security
      server: https://kubernetes.default.svc
    - namespace: istio-system
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc

  # Cluster resource whitelist
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: scheduling.k8s.io
      kind: PriorityClass
    - group: policy
      kind: PodSecurityPolicy
    - group: networking.k8s.io
      kind: IngressClass
    - group: storage.k8s.io
      kind: StorageClass

  # Namespace resource blacklist (sensitive resources)
  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange

  # Namespace resource whitelist
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"

  # Roles for project members
  roles:
    - name: developer
      description: Developer access to dev/staging
      policies:
        - p, proj:qbitel:developer, applications, get, qbitel/*, allow
        - p, proj:qbitel:developer, applications, create, qbitel/qbitel-dev-*, allow
        - p, proj:qbitel:developer, applications, update, qbitel/qbitel-dev-*, allow
        - p, proj:qbitel:developer, applications, delete, qbitel/qbitel-dev-*, allow
        - p, proj:qbitel:developer, applications, sync, qbitel/qbitel-dev-*, allow
        - p, proj:qbitel:developer, applications, sync, qbitel/qbitel-staging-*, allow
      groups:
        - qbitel:developers

    - name: sre
      description: SRE access to all environments
      policies:
        - p, proj:qbitel:sre, applications, *, qbitel/*, allow
        - p, proj:qbitel:sre, logs, get, qbitel/*, allow
        - p, proj:qbitel:sre, exec, create, qbitel/*, allow
      groups:
        - qbitel:sre

    - name: viewer
      description: Read-only access
      policies:
        - p, proj:qbitel:viewer, applications, get, qbitel/*, allow
      groups:
        - qbitel:viewers

  # Sync windows for production
  syncWindows:
    # Allow syncs during business hours for non-prod
    - kind: allow
      schedule: "0 6 * * 1-5"  # Monday-Friday 6 AM
      duration: 12h
      applications:
        - qbitel-dev-*
        - qbitel-staging-*
      namespaces:
        - qbitel-dev
        - qbitel-staging

    # Deny production syncs during peak hours
    - kind: deny
      schedule: "0 9 * * 1-5"  # Monday-Friday 9 AM
      duration: 8h
      applications:
        - qbitel-prod-*
      namespaces:
        - qbitel-prod
      manualSync: true  # Allow manual sync

    # Allow production syncs during maintenance window
    - kind: allow
      schedule: "0 2 * * 0"  # Sunday 2 AM
      duration: 4h
      applications:
        - qbitel-prod-*
      namespaces:
        - qbitel-prod

  # Orphaned resources monitoring
  orphanedResources:
    warn: true
    ignore:
      - group: ""
        kind: ConfigMap
        name: kube-root-ca.crt

  # Signature keys for signed commits (optional)
  signatureKeys: []
