---
# ArgoCD ConfigMap - Custom Configuration for QBITEL
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Repository credentials (reference secrets)
  repositories: |
    - url: https://github.com/yazhsab/qbitel.git
      name: qbitel
      type: git
    - url: https://github.com/yazhsab/qbitel-config.git
      name: qbitel-config
      type: git

  # Resource customizations for QBITEL CRDs
  resource.customizations: |
    # Custom health checks for QBITEL resources
    qbitel.ai/ProtocolAdapter:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.phase == "Ready" then
            hs.status = "Healthy"
            hs.message = "Protocol adapter is ready"
          elseif obj.status.phase == "Progressing" then
            hs.status = "Progressing"
            hs.message = "Protocol adapter is starting"
          else
            hs.status = "Degraded"
            hs.message = obj.status.message or "Unknown status"
          end
        else
          hs.status = "Progressing"
          hs.message = "Waiting for status"
        end
        return hs

    qbitel.ai/SecurityPolicy:
      health.lua: |
        hs = {}
        if obj.status ~= nil and obj.status.enforced then
          hs.status = "Healthy"
          hs.message = "Security policy enforced"
        else
          hs.status = "Progressing"
          hs.message = "Policy not yet enforced"
        end
        return hs

    # KServe InferenceService health
    serving.kserve.io/InferenceService:
      health.lua: |
        hs = {}
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do
              if condition.type == "Ready" and condition.status == "True" then
                hs.status = "Healthy"
                hs.message = "InferenceService is ready"
                return hs
              end
            end
          end
          hs.status = "Progressing"
          hs.message = "InferenceService starting"
        else
          hs.status = "Progressing"
          hs.message = "Waiting for status"
        end
        return hs

  # Resource exclusions
  resource.exclusions: |
    - apiGroups:
        - "events.k8s.io"
      kinds:
        - Event
      clusters:
        - "*"

  # Dex configuration for SSO (optional)
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: $dex.github.clientID
          clientSecret: $dex.github.clientSecret
          orgs:
            - name: qbitel

  # Application controller settings
  application.instanceLabelKey: argocd.argoproj.io/instance

  # Timeout settings
  timeout.reconciliation: 180s
  timeout.hard.reconciliation: 0s

  # Admin settings
  admin.enabled: "true"

  # Status badge
  statusbadge.enabled: "true"

  # Kustomize build options
  kustomize.buildOptions: --enable-helm
---
# ArgoCD RBAC ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    # QBITEL GitOps RBAC Policies

    # Admin role - full access
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, accounts, *, *, allow
    p, role:admin, gpgkeys, *, *, allow
    p, role:admin, logs, *, *, allow
    p, role:admin, exec, *, */*, allow

    # Developer role - deploy to dev/staging
    p, role:developer, applications, get, */*, allow
    p, role:developer, applications, create, qbitel-dev/*, allow
    p, role:developer, applications, update, qbitel-dev/*, allow
    p, role:developer, applications, delete, qbitel-dev/*, allow
    p, role:developer, applications, sync, qbitel-dev/*, allow
    p, role:developer, applications, create, qbitel-staging/*, allow
    p, role:developer, applications, update, qbitel-staging/*, allow
    p, role:developer, applications, sync, qbitel-staging/*, allow
    p, role:developer, logs, get, qbitel-dev/*, allow
    p, role:developer, logs, get, qbitel-staging/*, allow

    # SRE role - production access
    p, role:sre, applications, *, */*, allow
    p, role:sre, clusters, get, *, allow
    p, role:sre, repositories, get, *, allow
    p, role:sre, logs, get, */*, allow
    p, role:sre, exec, create, */*, allow

    # Read-only role
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, clusters, get, *, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, projects, get, *, allow

    # Group mappings
    g, qbitel:admins, role:admin
    g, qbitel:developers, role:developer
    g, qbitel:sre, role:sre
    g, qbitel:viewers, role:readonly

  scopes: "[groups]"
