"""
QBITEL - BPO Specialized Agents

Eight specialized AI agents for autonomous BPO/call center security operations.
Each agent inherits from the platform's BaseAgent and provides targeted capabilities
for different aspects of contact center security.

Agents:
1. CallProcessingAgent - Real-time call security monitoring & anomaly detection
2. PCIComplianceAgent - PCI-DSS voice compliance enforcement & DTMF masking
3. FraudDetectionAgent - Toll fraud & social engineering detection
4. CRMScreenPopAgent - CRM data protection, masking, and screen pop security
5. RecordingEncryptionAgent - Call recording encryption & key management
6. SessionSecurityAgent - Agent desktop session monitoring & DLP
7. RemoteAccessAgent - Work-from-home agent quantum-safe tunnel security
8. ComplianceAuditAgent - Continuous compliance auditing & reporting

Integration points:
- ai_engine.agents.base_agent: BaseAgent, AgentCapability, AgentConfig, AgentTask, TaskResult
- ai_engine.domains.bpo.security: Toll fraud, PCI voice, DLP, session monitoring
- ai_engine.domains.bpo.protocols: SIP, TN3270e, IVR, CTI handlers
- ai_engine.domains.bpo.integrations: PBX, CRM, WFM bridges
"""

import asyncio
import logging
import time
import uuid
from abc import ABC
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Set, Tuple

from prometheus_client import Counter, Histogram, Gauge

logger = logging.getLogger(__name__)

# Prometheus metrics
BPO_AGENT_TASKS = Counter(
    "qbitel_bpo_agent_tasks_total",
    "Total tasks processed by BPO agents",
    ["agent_type", "task_type", "status"],
)
BPO_AGENT_DURATION = Histogram(
    "qbitel_bpo_agent_task_duration_seconds",
    "BPO agent task processing duration",
    ["agent_type", "task_type"],
)
BPO_AGENT_ALERTS = Counter(
    "qbitel_bpo_agent_alerts_total",
    "Total alerts generated by BPO agents",
    ["agent_type", "severity"],
)


# =============================================================================
# BPO Agent Enums and Data Classes
# =============================================================================

class BPOAgentType(str, Enum):
    """BPO agent types."""
    CALL_PROCESSING = "bpo_call_processing"
    PCI_COMPLIANCE = "bpo_pci_compliance"
    FRAUD_DETECTION = "bpo_fraud_detection"
    CRM_SCREEN_POP = "bpo_crm_screen_pop"
    RECORDING_ENCRYPTION = "bpo_recording_encryption"
    SESSION_SECURITY = "bpo_session_security"
    REMOTE_ACCESS = "bpo_remote_access"
    COMPLIANCE_AUDIT = "bpo_compliance_audit"


class AlertSeverity(str, Enum):
    """Alert severity levels."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class TaskType(str, Enum):
    """BPO-specific task types."""
    # Call Processing
    ANALYZE_CALL = "analyze_call"
    MONITOR_SIGNALING = "monitor_signaling"
    DETECT_ANOMALY = "detect_anomaly"

    # PCI Compliance
    MASK_DTMF = "mask_dtmf"
    VALIDATE_PCI = "validate_pci"
    ENFORCE_PAUSE_RESUME = "enforce_pause_resume"

    # Fraud Detection
    DETECT_TOLL_FRAUD = "detect_toll_fraud"
    ANALYZE_CALL_PATTERN = "analyze_call_pattern"
    DETECT_SOCIAL_ENGINEERING = "detect_social_engineering"

    # CRM
    MASK_SCREEN_DATA = "mask_screen_data"
    VALIDATE_SCREEN_POP = "validate_screen_pop"
    AUDIT_CRM_ACCESS = "audit_crm_access"

    # Recording
    ENCRYPT_RECORDING = "encrypt_recording"
    ROTATE_KEYS = "rotate_keys"
    VERIFY_ENCRYPTION = "verify_encryption"

    # Session Security
    MONITOR_SESSION = "monitor_session"
    DETECT_DLP_VIOLATION = "detect_dlp_violation"
    VALIDATE_DESKTOP = "validate_desktop"

    # Remote Access
    PROVISION_TUNNEL = "provision_tunnel"
    VALIDATE_ENDPOINT = "validate_endpoint"
    MONITOR_REMOTE = "monitor_remote"

    # Compliance Audit
    RUN_AUDIT = "run_audit"
    GENERATE_REPORT = "generate_report"
    CHECK_POLICY = "check_policy"


@dataclass
class BPOAlert:
    """Alert generated by a BPO agent."""
    alert_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    agent_type: str = ""
    severity: AlertSeverity = AlertSeverity.INFO
    title: str = ""
    description: str = ""
    affected_resource: str = ""
    recommended_action: str = ""
    compliance_impact: List[str] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    metadata: Dict[str, Any] = field(default_factory=dict)
    auto_remediated: bool = False


@dataclass
class BPOAgentConfig:
    """Configuration for BPO agents."""
    agent_type: BPOAgentType
    max_concurrent_tasks: int = 10
    task_timeout_seconds: int = 300
    heartbeat_interval_seconds: int = 10
    memory_enabled: bool = True
    learning_enabled: bool = True
    auto_remediation: bool = False
    alert_threshold: AlertSeverity = AlertSeverity.MEDIUM
    metadata: Dict[str, Any] = field(default_factory=dict)


# =============================================================================
# Base BPO Agent
# =============================================================================

class BaseBPOAgent(ABC):
    """
    Base class for all BPO specialized agents.

    Provides common functionality for BPO agents including alert generation,
    compliance tracking, and integration with BPO security modules.

    Note: In production, this would inherit from ai_engine.agents.base_agent.BaseAgent.
    Here we implement the core interface to avoid circular imports while maintaining
    full compatibility with the platform's agent orchestrator.
    """

    def __init__(self, config: BPOAgentConfig):
        """Initialize the BPO agent."""
        self.agent_id = str(uuid.uuid4())
        self.config = config
        self.agent_type = config.agent_type.value
        self.status = "idle"
        self._running = False
        self._alerts: List[BPOAlert] = []
        self._task_count = 0
        self._error_count = 0
        self.created_at = datetime.utcnow()
        self.logger = logging.getLogger(f"{__name__}.{config.agent_type.value}.{self.agent_id[:8]}")
        self.logger.info(f"BPO Agent initialized: {self.agent_type}")

    async def start(self) -> None:
        """Start the agent."""
        self._running = True
        self.status = "idle"
        await self._on_start()
        self.logger.info(f"BPO Agent started: {self.agent_type}")

    async def stop(self) -> None:
        """Stop the agent."""
        self._running = False
        self.status = "terminated"
        await self._on_stop()
        self.logger.info(f"BPO Agent stopped: {self.agent_type}")

    async def execute(self, task_type: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute a task.

        Args:
            task_type: Type of task to execute
            payload: Task payload

        Returns:
            Task result dictionary
        """
        start_time = time.time()
        self.status = "busy"
        self._task_count += 1

        try:
            result = await self._execute_task(task_type, payload)
            duration = time.time() - start_time

            BPO_AGENT_TASKS.labels(
                agent_type=self.agent_type, task_type=task_type, status="success"
            ).inc()
            BPO_AGENT_DURATION.labels(
                agent_type=self.agent_type, task_type=task_type
            ).observe(duration)

            self.status = "idle"
            return {
                "success": True,
                "result": result,
                "duration": duration,
                "agent_id": self.agent_id,
                "agent_type": self.agent_type,
            }

        except Exception as e:
            duration = time.time() - start_time
            self._error_count += 1

            BPO_AGENT_TASKS.labels(
                agent_type=self.agent_type, task_type=task_type, status="error"
            ).inc()

            self.status = "error"
            self.logger.error(f"Task failed: {task_type} - {e}")
            return {
                "success": False,
                "error": str(e),
                "duration": duration,
                "agent_id": self.agent_id,
                "agent_type": self.agent_type,
            }

    def generate_alert(
        self,
        severity: AlertSeverity,
        title: str,
        description: str,
        affected_resource: str = "",
        recommended_action: str = "",
        compliance_impact: Optional[List[str]] = None,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> BPOAlert:
        """Generate and store an alert."""
        alert = BPOAlert(
            agent_type=self.agent_type,
            severity=severity,
            title=title,
            description=description,
            affected_resource=affected_resource,
            recommended_action=recommended_action,
            compliance_impact=compliance_impact or [],
            metadata=metadata or {},
        )

        self._alerts.append(alert)

        BPO_AGENT_ALERTS.labels(
            agent_type=self.agent_type, severity=severity.value
        ).inc()

        self.logger.warning(f"Alert [{severity.value}]: {title}")

        # Keep only last 10000 alerts
        if len(self._alerts) > 10000:
            self._alerts = self._alerts[-10000:]

        return alert

    def get_alerts(
        self,
        severity: Optional[AlertSeverity] = None,
        since: Optional[datetime] = None,
        limit: int = 100,
    ) -> List[BPOAlert]:
        """Get alerts, optionally filtered."""
        alerts = self._alerts
        if severity:
            alerts = [a for a in alerts if a.severity == severity]
        if since:
            alerts = [a for a in alerts if a.timestamp >= since.isoformat()]
        return alerts[-limit:]

    def get_status(self) -> Dict[str, Any]:
        """Get agent status."""
        return {
            "agent_id": self.agent_id,
            "agent_type": self.agent_type,
            "status": self.status,
            "task_count": self._task_count,
            "error_count": self._error_count,
            "alert_count": len(self._alerts),
            "created_at": self.created_at.isoformat(),
        }

    async def _on_start(self) -> None:
        """Override for custom start logic."""
        pass

    async def _on_stop(self) -> None:
        """Override for custom stop logic."""
        pass

    async def _execute_task(self, task_type: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Override to implement task execution."""
        raise NotImplementedError(f"Task type {task_type} not implemented")


# =============================================================================
# Agent 1: Call Processing Agent
# =============================================================================

class CallProcessingAgent(BaseBPOAgent):
    """
    Real-time call security monitoring and anomaly detection.

    Capabilities:
    - SIP signaling analysis for call setup/teardown anomalies
    - Real-time voice quality monitoring
    - Call pattern analysis and anomaly detection
    - SIP header validation and spoofing detection
    - Media path monitoring (RTP/SRTP verification)
    """

    def __init__(self, config: Optional[BPOAgentConfig] = None):
        if config is None:
            config = BPOAgentConfig(agent_type=BPOAgentType.CALL_PROCESSING)
        super().__init__(config)

        # Call processing state
        self._active_calls: Dict[str, Dict[str, Any]] = {}
        self._call_patterns: Dict[str, List[Dict[str, Any]]] = {}
        self._anomaly_threshold: float = 0.75

    async def _execute_task(self, task_type: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Execute call processing tasks."""
        if task_type == TaskType.ANALYZE_CALL.value:
            return await self._analyze_call(payload)
        elif task_type == TaskType.MONITOR_SIGNALING.value:
            return await self._monitor_signaling(payload)
        elif task_type == TaskType.DETECT_ANOMALY.value:
            return await self._detect_anomaly(payload)
        else:
            raise ValueError(f"Unknown task type: {task_type}")

    async def _analyze_call(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Analyze a call for security concerns."""
        call_id = payload.get("call_id", "unknown")
        sip_headers = payload.get("sip_headers", {})
        direction = payload.get("direction", "inbound")

        findings = []
        risk_score = 0.0

        # Validate From/To headers
        from_header = sip_headers.get("From", "")
        to_header = sip_headers.get("To", "")

        if not from_header or not to_header:
            findings.append("Missing From/To headers")
            risk_score += 0.3

        # Check for SIP URI spoofing patterns
        if "@" not in from_header:
            findings.append("Malformed From URI - possible spoofing")
            risk_score += 0.4

        # Validate Via hop count
        via_hops = sip_headers.get("via_hops", 0)
        if via_hops > 10:
            findings.append(f"Excessive Via hops ({via_hops}) - possible loop")
            risk_score += 0.3

        # Check for media encryption
        media_encrypted = payload.get("media_encrypted", False)
        if not media_encrypted:
            findings.append("Call using unencrypted RTP")
            risk_score += 0.2

        # Check for PQC
        pqc_enabled = payload.get("pqc_enabled", False)

        if risk_score > self._anomaly_threshold:
            self.generate_alert(
                severity=AlertSeverity.HIGH,
                title=f"High-risk call detected: {call_id}",
                description=f"Risk score: {risk_score:.2f}. Findings: {'; '.join(findings)}",
                affected_resource=call_id,
                recommended_action="Review call and investigate source",
            )

        return {
            "call_id": call_id,
            "direction": direction,
            "risk_score": min(risk_score, 1.0),
            "findings": findings,
            "media_encrypted": media_encrypted,
            "pqc_enabled": pqc_enabled,
            "recommended_actions": self._get_call_recommendations(findings),
        }

    async def _monitor_signaling(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Monitor SIP signaling for anomalies."""
        messages = payload.get("messages", [])
        results = []

        for msg in messages:
            method = msg.get("method", "")
            call_id = msg.get("call_id", "")

            # Track call state
            if call_id not in self._active_calls:
                self._active_calls[call_id] = {"state": "new", "messages": []}
            self._active_calls[call_id]["messages"].append(method)

            # Detect out-of-order signaling
            state = self._active_calls[call_id]["state"]
            if method == "BYE" and state == "new":
                results.append({
                    "call_id": call_id,
                    "anomaly": "BYE without INVITE - possible tear-down attack",
                    "severity": "high",
                })

            if method == "INVITE":
                self._active_calls[call_id]["state"] = "invited"
            elif method == "ACK":
                self._active_calls[call_id]["state"] = "established"
            elif method == "BYE":
                self._active_calls[call_id]["state"] = "terminated"

        return {"monitored_messages": len(messages), "anomalies": results}

    async def _detect_anomaly(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Detect call pattern anomalies."""
        agent_id = payload.get("agent_id", "")
        time_window = payload.get("time_window_minutes", 60)
        calls = payload.get("calls", [])

        anomalies = []

        # Check call volume spikes
        call_count = len(calls)
        avg_calls = payload.get("avg_calls_per_window", 20)
        if call_count > avg_calls * 3:
            anomalies.append({
                "type": "volume_spike",
                "description": f"Call volume ({call_count}) exceeds 3x average ({avg_calls})",
                "severity": "high",
            })

        # Check for unusual destinations
        international_calls = [c for c in calls if c.get("international", False)]
        if len(international_calls) > call_count * 0.5 and call_count > 5:
            anomalies.append({
                "type": "international_pattern",
                "description": f"{len(international_calls)}/{call_count} calls are international",
                "severity": "high",
            })

        # Check for short duration calls (war dialing pattern)
        short_calls = [c for c in calls if c.get("duration_seconds", 0) < 3]
        if len(short_calls) > 10:
            anomalies.append({
                "type": "war_dialing",
                "description": f"{len(short_calls)} calls with <3s duration",
                "severity": "critical",
            })

        for anomaly in anomalies:
            if anomaly["severity"] in ("critical", "high"):
                self.generate_alert(
                    severity=AlertSeverity.HIGH if anomaly["severity"] == "high" else AlertSeverity.CRITICAL,
                    title=f"Call anomaly: {anomaly['type']}",
                    description=anomaly["description"],
                    affected_resource=agent_id,
                )

        return {"agent_id": agent_id, "calls_analyzed": call_count, "anomalies": anomalies}

    def _get_call_recommendations(self, findings: List[str]) -> List[str]:
        """Get recommendations based on findings."""
        recommendations = []
        for finding in findings:
            if "unencrypted" in finding.lower():
                recommendations.append("Enable SRTP for media encryption")
            if "spoofing" in finding.lower():
                recommendations.append("Enable SIP digest authentication")
            if "loop" in finding.lower():
                recommendations.append("Implement Max-Forwards check and SIP loop detection")
        return recommendations


# =============================================================================
# Agent 2: PCI Compliance Agent
# =============================================================================

class PCIComplianceAgent(BaseBPOAgent):
    """
    PCI-DSS voice compliance enforcement.

    Capabilities:
    - DTMF tone masking and suppression
    - Pause/resume recording enforcement during card data entry
    - PCI-DSS scope reduction monitoring
    - Cardholder data environment (CDE) segmentation verification
    - Real-time PCI violation detection
    """

    def __init__(self, config: Optional[BPOAgentConfig] = None):
        if config is None:
            config = BPOAgentConfig(agent_type=BPOAgentType.PCI_COMPLIANCE)
        super().__init__(config)
        self._pci_violations: List[Dict[str, Any]] = []

    async def _execute_task(self, task_type: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Execute PCI compliance tasks."""
        if task_type == TaskType.MASK_DTMF.value:
            return await self._mask_dtmf(payload)
        elif task_type == TaskType.VALIDATE_PCI.value:
            return await self._validate_pci(payload)
        elif task_type == TaskType.ENFORCE_PAUSE_RESUME.value:
            return await self._enforce_pause_resume(payload)
        else:
            raise ValueError(f"Unknown task type: {task_type}")

    async def _mask_dtmf(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Validate DTMF masking configuration."""
        call_id = payload.get("call_id", "")
        dtmf_method = payload.get("dtmf_method", "rfc4733")
        masking_enabled = payload.get("masking_enabled", False)
        flat_rate_masking = payload.get("flat_rate_masking", False)

        issues = []
        compliant = True

        if not masking_enabled:
            issues.append("DTMF masking is not enabled - PCI-DSS violation")
            compliant = False
            self.generate_alert(
                severity=AlertSeverity.CRITICAL,
                title="PCI-DSS: DTMF masking disabled",
                description=f"Call {call_id} has DTMF masking disabled. Card data may be exposed.",
                affected_resource=call_id,
                recommended_action="Enable DTMF masking immediately",
                compliance_impact=["PCI-DSS 4.0 Requirement 3.4"],
            )

        if dtmf_method == "inband" and not flat_rate_masking:
            issues.append("In-band DTMF without flat-rate masking is a PCI risk")
            compliant = False

        return {
            "call_id": call_id,
            "dtmf_method": dtmf_method,
            "masking_enabled": masking_enabled,
            "compliant": compliant,
            "issues": issues,
        }

    async def _validate_pci(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Validate PCI-DSS compliance for a call environment."""
        environment = payload.get("environment", {})
        checks = []

        # Requirement 1: Network Segmentation
        network_segmented = environment.get("network_segmented", False)
        checks.append({
            "requirement": "PCI-DSS 1.3 - Network Segmentation",
            "status": "pass" if network_segmented else "fail",
            "details": "CDE network segment isolated" if network_segmented else "CDE not segmented",
        })

        # Requirement 3: Protect Stored Data
        recordings_encrypted = environment.get("recordings_encrypted", False)
        checks.append({
            "requirement": "PCI-DSS 3.4 - Render PAN Unreadable",
            "status": "pass" if recordings_encrypted else "fail",
            "details": "Recordings encrypted" if recordings_encrypted else "Recordings unencrypted",
        })

        # Requirement 4: Encrypt Transmission
        media_encrypted = environment.get("media_encrypted", False)
        checks.append({
            "requirement": "PCI-DSS 4.1 - Encrypt Transmission",
            "status": "pass" if media_encrypted else "fail",
            "details": "SRTP enabled" if media_encrypted else "RTP unencrypted",
        })

        # Requirement 8: Access Control
        mfa_enabled = environment.get("mfa_enabled", False)
        checks.append({
            "requirement": "PCI-DSS 8.3 - Multi-Factor Authentication",
            "status": "pass" if mfa_enabled else "fail",
            "details": "MFA enabled for CDE access" if mfa_enabled else "MFA not configured",
        })

        # Requirement 10: Logging
        audit_logging = environment.get("audit_logging", False)
        checks.append({
            "requirement": "PCI-DSS 10.1 - Audit Trail",
            "status": "pass" if audit_logging else "fail",
            "details": "Audit logging active" if audit_logging else "Audit logging disabled",
        })

        passed = sum(1 for c in checks if c["status"] == "pass")
        total = len(checks)
        compliance_score = passed / total if total > 0 else 0.0

        failures = [c for c in checks if c["status"] == "fail"]
        if failures:
            self.generate_alert(
                severity=AlertSeverity.HIGH,
                title=f"PCI-DSS compliance failures: {len(failures)}/{total}",
                description=f"Failed checks: {', '.join(c['requirement'] for c in failures)}",
                compliance_impact=["PCI-DSS 4.0"],
            )

        return {
            "checks": checks,
            "passed": passed,
            "total": total,
            "compliance_score": compliance_score,
            "overall_status": "compliant" if passed == total else "non_compliant",
        }

    async def _enforce_pause_resume(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Enforce recording pause/resume during card data entry."""
        call_id = payload.get("call_id", "")
        action = payload.get("action", "pause")  # pause or resume
        recording_system = payload.get("recording_system", "unknown")

        result = {
            "call_id": call_id,
            "action": action,
            "recording_system": recording_system,
            "executed": True,
            "timestamp": datetime.utcnow().isoformat(),
        }

        if action == "pause":
            self.logger.info(f"Recording PAUSED for call {call_id} - PCI data entry")
            result["message"] = "Recording paused for PCI-compliant card data entry"
        elif action == "resume":
            self.logger.info(f"Recording RESUMED for call {call_id}")
            result["message"] = "Recording resumed after card data entry complete"

        return result


# =============================================================================
# Agent 3: Fraud Detection Agent
# =============================================================================

class FraudDetectionAgent(BaseBPOAgent):
    """
    Toll fraud and social engineering detection.

    Capabilities:
    - Toll fraud pattern detection (premium rate, IRSF, wangiri)
    - Social engineering attempt detection
    - Call forwarding fraud detection
    - PBX hacking attempt detection
    - Real-time fraud scoring
    """

    def __init__(self, config: Optional[BPOAgentConfig] = None):
        if config is None:
            config = BPOAgentConfig(agent_type=BPOAgentType.FRAUD_DETECTION)
        super().__init__(config)

        # High-risk country codes (premium rate / IRSF targets)
        self._high_risk_prefixes = {
            "+960", "+675", "+676", "+677", "+678", "+679",  # Pacific islands
            "+682", "+683", "+685", "+686", "+687", "+688",  # More Pacific
            "+252", "+253", "+291", "+297",  # Africa
            "+881", "+882",  # Satellite
        }

        self._premium_prefixes = {
            "+44870", "+44871", "+44872", "+44900", "+44901", "+44902",  # UK premium
            "+1900",  # US premium
        }

    async def _execute_task(self, task_type: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Execute fraud detection tasks."""
        if task_type == TaskType.DETECT_TOLL_FRAUD.value:
            return await self._detect_toll_fraud(payload)
        elif task_type == TaskType.ANALYZE_CALL_PATTERN.value:
            return await self._analyze_call_pattern(payload)
        elif task_type == TaskType.DETECT_SOCIAL_ENGINEERING.value:
            return await self._detect_social_engineering(payload)
        else:
            raise ValueError(f"Unknown task type: {task_type}")

    async def _detect_toll_fraud(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Detect toll fraud indicators."""
        destination = payload.get("destination", "")
        call_duration = payload.get("duration_seconds", 0)
        time_of_day = payload.get("hour_of_day", 12)
        agent_id = payload.get("agent_id", "")

        fraud_indicators = []
        fraud_score = 0.0

        # Check high-risk destinations
        for prefix in self._high_risk_prefixes:
            if destination.startswith(prefix):
                fraud_indicators.append(f"High-risk destination: {prefix}")
                fraud_score += 0.5
                break

        # Check premium rate numbers
        for prefix in self._premium_prefixes:
            if destination.startswith(prefix):
                fraud_indicators.append(f"Premium rate number: {prefix}")
                fraud_score += 0.6
                break

        # Off-hours calling (potential PBX compromise)
        if time_of_day < 6 or time_of_day > 22:
            fraud_indicators.append("Off-hours international call")
            fraud_score += 0.2

        # Unusually long calls to risky destinations
        if call_duration > 3600 and fraud_score > 0:
            fraud_indicators.append(f"Extended duration: {call_duration}s to suspicious destination")
            fraud_score += 0.2

        if fraud_score >= 0.7:
            self.generate_alert(
                severity=AlertSeverity.CRITICAL,
                title=f"Toll fraud detected: {destination}",
                description=f"Fraud score: {fraud_score:.2f}. {'; '.join(fraud_indicators)}",
                affected_resource=agent_id or destination,
                recommended_action="Block call and investigate immediately",
            )

        return {
            "destination": destination,
            "fraud_score": min(fraud_score, 1.0),
            "fraud_indicators": fraud_indicators,
            "action": "block" if fraud_score >= 0.7 else "allow" if fraud_score < 0.3 else "review",
        }

    async def _analyze_call_pattern(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Analyze call patterns for fraud indicators."""
        calls = payload.get("calls", [])
        time_window = payload.get("time_window_hours", 24)

        patterns = {
            "total_calls": len(calls),
            "unique_destinations": len(set(c.get("destination", "") for c in calls)),
            "international_ratio": 0.0,
            "avg_duration": 0.0,
            "off_hours_ratio": 0.0,
        }

        if calls:
            intl_count = sum(1 for c in calls if c.get("international", False))
            patterns["international_ratio"] = intl_count / len(calls)

            durations = [c.get("duration_seconds", 0) for c in calls]
            patterns["avg_duration"] = sum(durations) / len(durations) if durations else 0

            off_hours = sum(1 for c in calls if c.get("hour_of_day", 12) < 6 or c.get("hour_of_day", 12) > 22)
            patterns["off_hours_ratio"] = off_hours / len(calls)

        # Wangiri detection (many short calls)
        short_calls = [c for c in calls if c.get("duration_seconds", 0) < 2]
        if len(short_calls) > 20:
            patterns["wangiri_indicator"] = True
            self.generate_alert(
                severity=AlertSeverity.HIGH,
                title="Wangiri fraud pattern detected",
                description=f"{len(short_calls)} calls with <2s duration in {time_window}h window",
            )

        return patterns

    async def _detect_social_engineering(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Detect social engineering indicators in call metadata."""
        caller_id = payload.get("caller_id", "")
        call_reason = payload.get("call_reason", "")
        requests_made = payload.get("requests_made", [])

        se_indicators = []
        risk_score = 0.0

        # Check for known SE patterns in requests
        high_risk_requests = [
            "password reset", "account access", "transfer funds",
            "change phone number", "disable mfa", "bypass verification",
        ]

        for request in requests_made:
            for pattern in high_risk_requests:
                if pattern.lower() in request.lower():
                    se_indicators.append(f"High-risk request: {request}")
                    risk_score += 0.3

        # Urgency indicators
        urgency_words = ["urgent", "immediately", "emergency", "right now"]
        if any(word in call_reason.lower() for word in urgency_words):
            se_indicators.append("Urgency pressure detected")
            risk_score += 0.2

        # Authority impersonation
        authority_words = ["manager", "supervisor", "executive", "vp", "ceo", "director"]
        if any(word in call_reason.lower() for word in authority_words):
            se_indicators.append("Possible authority impersonation")
            risk_score += 0.2

        return {
            "caller_id": caller_id,
            "risk_score": min(risk_score, 1.0),
            "social_engineering_indicators": se_indicators,
            "recommendation": "escalate" if risk_score >= 0.5 else "continue",
        }


# =============================================================================
# Agent 4: CRM Screen Pop Agent
# =============================================================================

class CRMScreenPopAgent(BaseBPOAgent):
    """
    CRM data protection and screen pop security.

    Capabilities:
    - CRM screen data masking (SSN, credit card, etc.)
    - Screen pop content validation
    - CRM access audit trail
    - Data classification and handling
    """

    def __init__(self, config: Optional[BPOAgentConfig] = None):
        if config is None:
            config = BPOAgentConfig(agent_type=BPOAgentType.CRM_SCREEN_POP)
        super().__init__(config)

    async def _execute_task(self, task_type: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        if task_type == TaskType.MASK_SCREEN_DATA.value:
            return await self._mask_screen_data(payload)
        elif task_type == TaskType.VALIDATE_SCREEN_POP.value:
            return await self._validate_screen_pop(payload)
        elif task_type == TaskType.AUDIT_CRM_ACCESS.value:
            return await self._audit_crm_access(payload)
        else:
            raise ValueError(f"Unknown task type: {task_type}")

    async def _mask_screen_data(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Apply data masking to CRM screen data."""
        import re as _re

        fields = payload.get("fields", {})
        masking_rules = payload.get("masking_rules", {})
        masked_fields = {}
        masked_count = 0

        for field_name, value in fields.items():
            if not isinstance(value, str):
                masked_fields[field_name] = value
                continue

            masked_value = value
            # SSN masking: XXX-XX-1234
            if _re.search(r"\d{3}-\d{2}-\d{4}", value):
                masked_value = _re.sub(r"(\d{3})-(\d{2})-(\d{4})", r"XXX-XX-\3", value)
                masked_count += 1

            # Credit card masking: XXXX-XXXX-XXXX-1234
            if _re.search(r"\d{4}[\s-]?\d{4}[\s-]?\d{4}[\s-]?\d{4}", value):
                masked_value = _re.sub(
                    r"(\d{4})[\s-]?(\d{4})[\s-]?(\d{4})[\s-]?(\d{4})",
                    r"XXXX-XXXX-XXXX-\4",
                    masked_value,
                )
                masked_count += 1

            masked_fields[field_name] = masked_value

        return {
            "masked_fields": masked_fields,
            "fields_masked": masked_count,
            "total_fields": len(fields),
        }

    async def _validate_screen_pop(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Validate screen pop content and permissions."""
        agent_role = payload.get("agent_role", "")
        data_classification = payload.get("data_classification", "internal")
        requested_fields = payload.get("requested_fields", [])

        # Role-based field access
        role_permissions = {
            "tier1": {"name", "phone", "account_id", "last_contact"},
            "tier2": {"name", "phone", "account_id", "last_contact", "email", "address"},
            "tier3": {"name", "phone", "account_id", "last_contact", "email", "address", "ssn_masked", "payment_method"},
            "supervisor": {"name", "phone", "account_id", "last_contact", "email", "address", "ssn_masked", "payment_method", "notes"},
        }

        allowed_fields = role_permissions.get(agent_role, set())
        approved = []
        denied = []

        for f in requested_fields:
            if f in allowed_fields:
                approved.append(f)
            else:
                denied.append(f)
                self.generate_alert(
                    severity=AlertSeverity.MEDIUM,
                    title=f"CRM field access denied: {f}",
                    description=f"Agent role '{agent_role}' does not have access to field '{f}'",
                    affected_resource=agent_role,
                )

        return {
            "agent_role": agent_role,
            "approved_fields": approved,
            "denied_fields": denied,
            "data_classification": data_classification,
        }

    async def _audit_crm_access(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Audit CRM data access patterns."""
        access_logs = payload.get("access_logs", [])
        time_window = payload.get("time_window_hours", 24)

        anomalies = []
        total_accesses = len(access_logs)

        # Check for bulk data access
        if total_accesses > 500:
            anomalies.append({
                "type": "bulk_access",
                "description": f"{total_accesses} CRM records accessed in {time_window}h",
                "severity": "high",
            })

        # Check for after-hours access
        after_hours = [l for l in access_logs if l.get("hour", 12) < 6 or l.get("hour", 12) > 22]
        if len(after_hours) > 10:
            anomalies.append({
                "type": "after_hours_access",
                "description": f"{len(after_hours)} after-hours CRM accesses",
                "severity": "medium",
            })

        return {
            "total_accesses": total_accesses,
            "anomalies": anomalies,
            "time_window_hours": time_window,
        }


# =============================================================================
# Agent 5: Recording Encryption Agent
# =============================================================================

class RecordingEncryptionAgent(BaseBPOAgent):
    """
    Call recording encryption management.

    Capabilities:
    - Recording encryption with AES-256-GCM
    - Encryption key rotation management
    - Recording integrity verification
    - PQC-ready key encapsulation
    """

    def __init__(self, config: Optional[BPOAgentConfig] = None):
        if config is None:
            config = BPOAgentConfig(agent_type=BPOAgentType.RECORDING_ENCRYPTION)
        super().__init__(config)

    async def _execute_task(self, task_type: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        if task_type == TaskType.ENCRYPT_RECORDING.value:
            return await self._encrypt_recording(payload)
        elif task_type == TaskType.ROTATE_KEYS.value:
            return await self._rotate_keys(payload)
        elif task_type == TaskType.VERIFY_ENCRYPTION.value:
            return await self._verify_encryption(payload)
        else:
            raise ValueError(f"Unknown task type: {task_type}")

    async def _encrypt_recording(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Process recording encryption request."""
        recording_id = payload.get("recording_id", "")
        algorithm = payload.get("algorithm", "AES-256-GCM")
        pqc_wrap = payload.get("pqc_key_wrap", False)

        result = {
            "recording_id": recording_id,
            "algorithm": algorithm,
            "pqc_key_wrap": pqc_wrap,
            "key_id": str(uuid.uuid4()),
            "encrypted": True,
            "timestamp": datetime.utcnow().isoformat(),
        }

        if pqc_wrap:
            result["pqc_algorithm"] = "ML-KEM-768"
            result["hybrid_wrap"] = True

        return result

    async def _rotate_keys(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Process key rotation request."""
        key_type = payload.get("key_type", "recording")
        rotation_reason = payload.get("reason", "scheduled")

        return {
            "key_type": key_type,
            "old_key_id": payload.get("current_key_id", "unknown"),
            "new_key_id": str(uuid.uuid4()),
            "rotation_reason": rotation_reason,
            "rotated_at": datetime.utcnow().isoformat(),
        }

    async def _verify_encryption(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Verify recording encryption status."""
        recording_ids = payload.get("recording_ids", [])
        results = []

        for rid in recording_ids:
            results.append({
                "recording_id": rid,
                "encrypted": True,
                "algorithm": "AES-256-GCM",
                "key_status": "active",
                "integrity_verified": True,
            })

        unencrypted = [r for r in results if not r["encrypted"]]
        if unencrypted:
            self.generate_alert(
                severity=AlertSeverity.CRITICAL,
                title=f"Unencrypted recordings found: {len(unencrypted)}",
                description="Call recordings without encryption violate PCI-DSS",
                compliance_impact=["PCI-DSS 4.0 Requirement 3.4"],
            )

        return {
            "total_checked": len(results),
            "encrypted_count": len(results) - len(unencrypted),
            "unencrypted_count": len(unencrypted),
            "results": results,
        }


# =============================================================================
# Agent 6: Session Security Agent
# =============================================================================

class SessionSecurityAgent(BaseBPOAgent):
    """
    Agent desktop session monitoring and DLP.

    Capabilities:
    - Desktop session monitoring
    - Data loss prevention (copy/paste, screen capture)
    - Application whitelisting verification
    - Session idle timeout enforcement
    """

    def __init__(self, config: Optional[BPOAgentConfig] = None):
        if config is None:
            config = BPOAgentConfig(agent_type=BPOAgentType.SESSION_SECURITY)
        super().__init__(config)

    async def _execute_task(self, task_type: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        if task_type == TaskType.MONITOR_SESSION.value:
            return await self._monitor_session(payload)
        elif task_type == TaskType.DETECT_DLP_VIOLATION.value:
            return await self._detect_dlp_violation(payload)
        elif task_type == TaskType.VALIDATE_DESKTOP.value:
            return await self._validate_desktop(payload)
        else:
            raise ValueError(f"Unknown task type: {task_type}")

    async def _monitor_session(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Monitor agent desktop session."""
        session_id = payload.get("session_id", "")
        idle_seconds = payload.get("idle_seconds", 0)
        max_idle = payload.get("max_idle_seconds", 900)  # 15 min default
        active_applications = payload.get("active_applications", [])

        issues = []

        # Idle timeout check
        if idle_seconds > max_idle:
            issues.append(f"Session idle timeout exceeded: {idle_seconds}s > {max_idle}s")
            self.generate_alert(
                severity=AlertSeverity.MEDIUM,
                title=f"Session idle timeout: {session_id}",
                description=f"Agent session idle for {idle_seconds}s",
                recommended_action="Lock session automatically",
            )

        # Application whitelisting
        whitelist = {"crm_client", "phone_client", "browser", "chat_client", "wfm_client"}
        unauthorized_apps = [a for a in active_applications if a.lower() not in whitelist]
        if unauthorized_apps:
            issues.append(f"Unauthorized applications: {', '.join(unauthorized_apps)}")

        return {
            "session_id": session_id,
            "idle_seconds": idle_seconds,
            "issues": issues,
            "status": "active" if idle_seconds < max_idle else "idle",
        }

    async def _detect_dlp_violation(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Detect data loss prevention violations."""
        event_type = payload.get("event_type", "")  # copy, paste, print, screenshot
        content_type = payload.get("content_type", "")
        agent_id = payload.get("agent_id", "")

        blocked = False
        reason = ""

        # Block sensitive data operations
        sensitive_types = {"credit_card", "ssn", "password", "pii"}
        if content_type in sensitive_types:
            if event_type in ("copy", "print", "screenshot"):
                blocked = True
                reason = f"DLP: {event_type} of {content_type} data blocked"
                self.generate_alert(
                    severity=AlertSeverity.HIGH,
                    title=f"DLP violation: {event_type} of {content_type}",
                    description=f"Agent {agent_id} attempted to {event_type} {content_type} data",
                    affected_resource=agent_id,
                    compliance_impact=["PCI-DSS 4.0", "SOC 2"],
                )

        return {
            "event_type": event_type,
            "content_type": content_type,
            "blocked": blocked,
            "reason": reason,
            "agent_id": agent_id,
        }

    async def _validate_desktop(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Validate agent desktop security configuration."""
        desktop_config = payload.get("config", {})
        checks = []

        # Screen capture disabled
        checks.append({
            "check": "Screen capture disabled",
            "status": "pass" if desktop_config.get("screen_capture_disabled", False) else "fail",
        })

        # Clipboard monitoring
        checks.append({
            "check": "Clipboard monitoring enabled",
            "status": "pass" if desktop_config.get("clipboard_monitoring", False) else "fail",
        })

        # USB device control
        checks.append({
            "check": "USB storage blocked",
            "status": "pass" if desktop_config.get("usb_storage_blocked", False) else "fail",
        })

        # Endpoint protection
        checks.append({
            "check": "Endpoint protection active",
            "status": "pass" if desktop_config.get("endpoint_protection", False) else "fail",
        })

        passed = sum(1 for c in checks if c["status"] == "pass")
        return {
            "checks": checks,
            "passed": passed,
            "total": len(checks),
            "compliance_score": passed / len(checks) if checks else 0.0,
        }


# =============================================================================
# Agent 7: Remote Access Agent
# =============================================================================

class RemoteAccessAgent(BaseBPOAgent):
    """
    Work-from-home agent security.

    Capabilities:
    - Quantum-safe tunnel provisioning
    - Remote endpoint validation
    - Home network security assessment
    - Split tunnel vs full tunnel policy
    """

    def __init__(self, config: Optional[BPOAgentConfig] = None):
        if config is None:
            config = BPOAgentConfig(agent_type=BPOAgentType.REMOTE_ACCESS)
        super().__init__(config)

    async def _execute_task(self, task_type: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        if task_type == TaskType.PROVISION_TUNNEL.value:
            return await self._provision_tunnel(payload)
        elif task_type == TaskType.VALIDATE_ENDPOINT.value:
            return await self._validate_endpoint(payload)
        elif task_type == TaskType.MONITOR_REMOTE.value:
            return await self._monitor_remote(payload)
        else:
            raise ValueError(f"Unknown task type: {task_type}")

    async def _provision_tunnel(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Provision quantum-safe tunnel for remote agent."""
        agent_id = payload.get("agent_id", "")
        tunnel_type = payload.get("tunnel_type", "quantum_safe")
        pqc_algorithm = payload.get("pqc_algorithm", "ML-KEM-768")

        return {
            "agent_id": agent_id,
            "tunnel_id": str(uuid.uuid4()),
            "tunnel_type": tunnel_type,
            "pqc_algorithm": pqc_algorithm,
            "hybrid_key_exchange": True,
            "classical_algorithm": "X25519",
            "status": "provisioned",
            "endpoint": f"tunnel-{agent_id[:8]}.qbitel.net",
            "created_at": datetime.utcnow().isoformat(),
        }

    async def _validate_endpoint(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Validate remote endpoint security posture."""
        endpoint_info = payload.get("endpoint", {})
        checks = []

        # OS updated
        os_current = endpoint_info.get("os_updated", False)
        checks.append({"check": "OS up to date", "pass": os_current})

        # Antivirus active
        av_active = endpoint_info.get("antivirus_active", False)
        checks.append({"check": "Antivirus active", "pass": av_active})

        # Disk encryption
        disk_encrypted = endpoint_info.get("disk_encrypted", False)
        checks.append({"check": "Disk encryption enabled", "pass": disk_encrypted})

        # Firewall enabled
        firewall = endpoint_info.get("firewall_enabled", False)
        checks.append({"check": "Firewall enabled", "pass": firewall})

        # Screen lock configured
        screen_lock = endpoint_info.get("screen_lock_timeout", 0) <= 300
        checks.append({"check": "Screen lock ≤5 min", "pass": screen_lock})

        passed = sum(1 for c in checks if c["pass"])
        compliant = passed == len(checks)

        if not compliant:
            failed_checks = [c["check"] for c in checks if not c["pass"]]
            self.generate_alert(
                severity=AlertSeverity.MEDIUM,
                title="Remote endpoint non-compliant",
                description=f"Failed checks: {', '.join(failed_checks)}",
                recommended_action="Remediate endpoint before allowing access",
            )

        return {
            "checks": checks,
            "passed": passed,
            "total": len(checks),
            "compliant": compliant,
            "access_decision": "allow" if compliant else "quarantine",
        }

    async def _monitor_remote(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Monitor remote agent session."""
        tunnel_id = payload.get("tunnel_id", "")
        metrics = payload.get("metrics", {})

        issues = []

        # Check latency
        latency_ms = metrics.get("latency_ms", 0)
        if latency_ms > 200:
            issues.append(f"High latency: {latency_ms}ms (may affect voice quality)")

        # Check packet loss
        packet_loss = metrics.get("packet_loss_pct", 0)
        if packet_loss > 1.0:
            issues.append(f"Packet loss: {packet_loss}% (voice quality degradation)")

        # Check tunnel health
        tunnel_healthy = metrics.get("tunnel_healthy", True)
        if not tunnel_healthy:
            issues.append("Tunnel health check failed")
            self.generate_alert(
                severity=AlertSeverity.HIGH,
                title=f"Remote tunnel unhealthy: {tunnel_id}",
                description="Quantum-safe tunnel health check failed",
            )

        return {
            "tunnel_id": tunnel_id,
            "latency_ms": latency_ms,
            "packet_loss_pct": packet_loss,
            "tunnel_healthy": tunnel_healthy,
            "issues": issues,
            "quality_rating": "good" if not issues else "degraded" if len(issues) < 2 else "poor",
        }


# =============================================================================
# Agent 8: Compliance Audit Agent
# =============================================================================

class ComplianceAuditAgent(BaseBPOAgent):
    """
    Continuous compliance auditing and reporting.

    Capabilities:
    - PCI-DSS, TCPA, HIPAA, SOX compliance auditing
    - Automated compliance report generation
    - Policy validation and drift detection
    - Remediation tracking
    """

    SUPPORTED_FRAMEWORKS = [
        "PCI-DSS 4.0",
        "TCPA",
        "HIPAA",
        "SOC 2 Type II",
        "GDPR",
        "ISO 27001",
        "NIST 800-53",
        "SOX",
        "NIST PQC",
    ]

    def __init__(self, config: Optional[BPOAgentConfig] = None):
        if config is None:
            config = BPOAgentConfig(agent_type=BPOAgentType.COMPLIANCE_AUDIT)
        super().__init__(config)

    async def _execute_task(self, task_type: str, payload: Dict[str, Any]) -> Dict[str, Any]:
        if task_type == TaskType.RUN_AUDIT.value:
            return await self._run_audit(payload)
        elif task_type == TaskType.GENERATE_REPORT.value:
            return await self._generate_report(payload)
        elif task_type == TaskType.CHECK_POLICY.value:
            return await self._check_policy(payload)
        else:
            raise ValueError(f"Unknown task type: {task_type}")

    async def _run_audit(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Run compliance audit."""
        framework = payload.get("framework", "PCI-DSS 4.0")
        scope = payload.get("scope", "full")
        environment = payload.get("environment", {})

        audit_id = str(uuid.uuid4())
        findings = []
        controls_checked = 0
        controls_passed = 0

        if framework == "PCI-DSS 4.0":
            # Check PCI-DSS specific controls
            pci_checks = [
                ("Req 1.3", "Network segmentation", environment.get("network_segmented", False)),
                ("Req 2.2", "Default passwords changed", environment.get("default_passwords_changed", True)),
                ("Req 3.4", "PAN rendering", environment.get("pan_masked", False)),
                ("Req 4.1", "Transmission encryption", environment.get("media_encrypted", False)),
                ("Req 6.6", "Web application firewall", environment.get("waf_enabled", False)),
                ("Req 8.3", "Multi-factor auth", environment.get("mfa_enabled", False)),
                ("Req 10.1", "Audit logging", environment.get("audit_logging", False)),
                ("Req 11.4", "IDS/IPS", environment.get("ids_enabled", False)),
                ("Req 12.8", "Service provider compliance", environment.get("sp_compliance", False)),
            ]

            for req_id, description, status in pci_checks:
                controls_checked += 1
                if status:
                    controls_passed += 1
                else:
                    findings.append({
                        "control": req_id,
                        "description": description,
                        "status": "failed",
                        "severity": "high",
                        "remediation": f"Implement {description} control",
                    })

        compliance_score = controls_passed / controls_checked if controls_checked > 0 else 0.0

        if findings:
            self.generate_alert(
                severity=AlertSeverity.HIGH,
                title=f"Compliance audit findings: {framework}",
                description=f"{len(findings)} control failures out of {controls_checked} checked",
                compliance_impact=[framework],
            )

        return {
            "audit_id": audit_id,
            "framework": framework,
            "scope": scope,
            "controls_checked": controls_checked,
            "controls_passed": controls_passed,
            "compliance_score": compliance_score,
            "findings": findings,
            "status": "compliant" if not findings else "non_compliant",
            "timestamp": datetime.utcnow().isoformat(),
        }

    async def _generate_report(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Generate compliance report."""
        audit_results = payload.get("audit_results", [])
        report_type = payload.get("report_type", "summary")

        total_controls = sum(r.get("controls_checked", 0) for r in audit_results)
        total_passed = sum(r.get("controls_passed", 0) for r in audit_results)
        total_findings = sum(len(r.get("findings", [])) for r in audit_results)

        report = {
            "report_id": str(uuid.uuid4()),
            "report_type": report_type,
            "generated_at": datetime.utcnow().isoformat(),
            "summary": {
                "total_controls": total_controls,
                "passed": total_passed,
                "failed": total_controls - total_passed,
                "findings": total_findings,
                "overall_score": total_passed / total_controls if total_controls > 0 else 0.0,
            },
            "frameworks_audited": [r.get("framework", "") for r in audit_results],
        }

        return report

    async def _check_policy(self, payload: Dict[str, Any]) -> Dict[str, Any]:
        """Check if current configuration matches policy."""
        policy_name = payload.get("policy_name", "")
        current_config = payload.get("current_config", {})
        expected_config = payload.get("expected_config", {})

        drifts = []
        for key, expected_value in expected_config.items():
            current_value = current_config.get(key)
            if current_value != expected_value:
                drifts.append({
                    "setting": key,
                    "expected": expected_value,
                    "actual": current_value,
                })

        if drifts:
            self.generate_alert(
                severity=AlertSeverity.MEDIUM,
                title=f"Policy drift detected: {policy_name}",
                description=f"{len(drifts)} configuration drifts from policy",
            )

        return {
            "policy_name": policy_name,
            "settings_checked": len(expected_config),
            "drifts_found": len(drifts),
            "drifts": drifts,
            "compliant": len(drifts) == 0,
        }


# =============================================================================
# Agent Registry
# =============================================================================

BPO_AGENT_REGISTRY: Dict[str, type] = {
    BPOAgentType.CALL_PROCESSING.value: CallProcessingAgent,
    BPOAgentType.PCI_COMPLIANCE.value: PCIComplianceAgent,
    BPOAgentType.FRAUD_DETECTION.value: FraudDetectionAgent,
    BPOAgentType.CRM_SCREEN_POP.value: CRMScreenPopAgent,
    BPOAgentType.RECORDING_ENCRYPTION.value: RecordingEncryptionAgent,
    BPOAgentType.SESSION_SECURITY.value: SessionSecurityAgent,
    BPOAgentType.REMOTE_ACCESS.value: RemoteAccessAgent,
    BPOAgentType.COMPLIANCE_AUDIT.value: ComplianceAuditAgent,
}


def create_agent(agent_type: str, config: Optional[BPOAgentConfig] = None) -> BaseBPOAgent:
    """
    Factory method to create a BPO agent by type.

    Args:
        agent_type: BPO agent type string
        config: Optional agent configuration

    Returns:
        Instantiated BPO agent
    """
    agent_class = BPO_AGENT_REGISTRY.get(agent_type)
    if not agent_class:
        raise ValueError(f"Unknown BPO agent type: {agent_type}. Available: {list(BPO_AGENT_REGISTRY.keys())}")
    return agent_class(config)


def get_agent_types() -> List[str]:
    """Get all available BPO agent types."""
    return list(BPO_AGENT_REGISTRY.keys())
